### PR TITLE
fluro-113 hide first email trash

### PR DESCRIPTION
**Pull request by peter-subsplash**
- hide the trash icon on only the primary email for data coming from subsplash

SUBSPLASH:
image

NON-SUBSPLASH:
image

### CODE REVIEW

**Comment by peter-subsplash** [comment]
Closing this as the story apparently needs clarifying. https://subsplash.atlassian.net/browse/HUFFLEPUFF-113

**Comment by peter-subsplash** [comment]
Reopened this after clarification: https://subsplash.atlassian.net/browse/HUFFLEPUFF-113

**Review by calvinjkelly-ss — APPROVED** [review]

**Comment by peter-subsplash** [comment]
@calvinjkelly-ss , could you review again? I realized that I hadn't updated it with the subsplash-only part. Thanks!

**Comment by calvinjkelly-ss** [comment]
Looks good. Approved!

**Review by calvinjkelly-ss — APPROVED** [review]

**Pull request merged**
